image: node:10.15

stages:
#  - test
  - deploy-develop
  - develop-production

cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

before_script:
  - yarn
  - npm i -g firebase-tools
  - firebase -V
  - echo "REACT_APP_CHAINSERVICE_API_URL:" ${REACT_APP_CHAINSERVICE_API_URL}
  - echo "REACT_APP_STATECHAIN_API_URL:" ${REACT_APP_STATECHAIN_API_URL}

#test:
#  stage: test
#  script:
#    - echo Please fix you tests boys!
#  # - yarn test:ci

deploy-develop:
  stage: deploy-develop
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet-dev
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: develop
  only:
    - master

deploy-production:
  stage: develop-production
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: production
  only:
    - master
  when: manual
