image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

test:
  stage: test
  only:
    - master
  script:
    - yarn
    - yarn test:ci

deploy:
  stage: deploy
  only:
    - master
  script:
    - npm i -g firebase-tools
    - firebase -V
    - firebase deploy --token ${FIREBASE_TOKEN}
  
