image: node:10.15

stages:
  - deploy-develop-merge-request
  - deploy-develop-master
  - develop-production

cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

before_script:
  - echo "REACT_APP_CHAINSERVICE_API_URL:" ${REACT_APP_CHAINSERVICE_API_URL}
  - echo "REACT_APP_STATECHAIN_API_URL:" ${REACT_APP_STATECHAIN_API_URL}
  - yarn
  - npm i -g firebase-tools
  - firebase -V

deploy-develop-merge-request:
  stage: deploy-develop-merge-request
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet-dev
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: develop
  only:
    - merge_requests

deploy-develop-master:
  stage: deploy-develop-master
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet-dev
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: develop
  only:
    master
  when:
    - manual

deploy-production:
  stage: develop-production
  script:
    - firebase use --token ${FIREBASE_TOKEN} bepswap-testnet
    - firebase deploy --token ${FIREBASE_TOKEN}
  environment:
    name: production
  only:
    - master
  when: manual
