image: node:latest

stages:
  - test_and_deploy

cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

test_and_deploy:
  stage: test_and_deploy
  only:
    - development
  script:
    - yarn
    - yarn test:ci
    - npm i -g firebase-tools
    - firebase -V
    - firebase deploy --token ${FIREBASE_TOKEN} --project development
  